📦️ [kotlin] Replace prettier to ktlint

diff --git a/ghooks/pre-commit b/ghooks/pre-commit
--- a/ghooks/pre-commit
+++ b/ghooks/pre-commit
@@ -1,12 +1,12 @@
 #!/bin/bash
 set -e
 
-# if this fails, please run mvn prettier:write to reformat
-echo '[pre-commit] Prettier check the code format "mvn prettier:check" ...'
-if ! mvn -q prettier:check; then
-  echo_r "\n[ERROR] Prettier check failed."
-  echo -e "Please run \"mvn prettier:write\" to reformat\n"
+# if this fails, please run mvn ktlint:format to reformat
+echo '[pre-commit] Ktlint check the code format "mvn ktlint:check" ...'
+if ! mvn -q ktlint:check; then
+  echo_r "\n[ERROR] format check failed."
+  echo -e "Please run \"mvn ktlint:format\" to reformat\n"
   exit 1
 fi
 
-echo "[pre-commit] Prettier check ok"
+echo "[pre-commit] ktlint check ok"
